apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  namespace: shir
spec:
  storageClassName: ebs-sc-shir
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
